---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        iam.amazonaws.com/role: {{ .Values.assume_role }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.docker_registry }}/{{ .Values.name }}:{{ .Values.rev }}
          imagePullPolicy: Always
          resources:
            requests:
              memory: 512Mi
            limits:
              memory: 2048Mi
          ports:
            - containerPort: 8085
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8085
          env:
            - name: FORCE_UPDATE
              value: "{{ .Values.force_update | default 0 }}"
            - name: DPP_SETTINGS
              value: "/data/.settings-{{ .Values.env }}.json"
            - name: AWS_DEFAULT_REGION
              value: "{{ .Values.aws_region | default "us-west-2" }}"
            {{- range $key, $value := .Values }}{{ if hasPrefix "env_" $key }}
            - name: {{ $key | trimPrefix "env_" }}
              value: "{{ $value }}"
            {{- end }}{{- end }}
          volumeMounts:
            - name: settings-secrets
              mountPath: "/data"
              readOnly: true
      volumes:
        - name: settings-secrets
          secret:
            secretName: dino-park-packs
